[application]

[web.app]
base_path = "printmergegenerator"
out_dir = "docs"
title = "PrintMergeGenerator"

# include `assets` in web platform
[web.resource]
style = []
script = []

[web.resource.dev]
script = []
