name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # ✅ Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ✅ Step 2: Install Rust + wasm target
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true

      # ✅ Step 3: Cache dependencies
      - uses: Swatinem/rust-cache@v2

      # ✅ Step 4: Install Dioxus CLI
      - name: Install Dioxus CLI
        run: cargo install dioxus-cli

      # ✅ Step 5: Build the project
      - name: Build with Dioxus
        run: dx build --release

      # ✅ Step 6: Copy index.html to 404.html
      - name: Patch 404 page
        run: |
          cp target/dx/print-merge-generator/release/web/public/index.html target/dx/print-merge-generator/release/web/public/404.html

      # ✅ Step 7: Deploy to GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: target/dx/print-merge-generator/release/web/public
          clean: true
